---
- name: Check for composer.json in project root or project_subtree_path
  stat:
    path: "{{ deploy_helper.new_release_path }}/composer.json"
  register: composer_json

- name: Fail if composer.json not found
  fail:
    msg: "Unable to find a `composer.json` file in the root of '{{ deploy_helper.new_release_path }}'. Make sure your repo has a `composer.json` file in its root or edit `repo_subtree_path` for '{{ site }}' in `ezplatform_sites.yml` so it points to the directory with a `composer.json` file."
  when: not composer_json.stat.exists

- name: Setup packagist.com authentication
  composer:
    command: config
    arguments: --auth http-basic.repo.packagist.com token {{ project.packagist_token }}
    working_dir: "{{ deploy_helper.new_release_path }}"
  no_log: true
  when: project.packagist_token is defined

- name: Install Composer dependencies
  composer:
    classmap_authoritative: yes
    optimize_autoloader: yes
    no_scripts: yes
    no_dev: yes
    working_dir: "{{ deploy_helper.new_release_path }}"

- name: Copy parameters.yml
  synchronize:
    src: "{{ project_local_path }}/app/config/parameters.yml"
    dest: "{{ deploy_helper.new_release_path }}/app/config/parameters.yml"
    group: no
    owner: no
    rsync_opts: --chmod=Du=rwx,--chmod=Dg=rx,--chmod=Do=rx,--chmod=Fu=rw,--chmod=Fg=r,--chmod=Fo=r

- name: Symfony cache clear
  command: "php bin/console cache:clear --env={{ env }}"
  args:
    chdir: "{{ deploy_helper.new_release_path }}"

- name: Symfony assets install
  command: "php bin/console assets:install --symlink --env={{ env }}"
  args:
    chdir: "{{ deploy_helper.new_release_path }}"

- name: Bazinga js translation dump
  command: "php bin/console bazinga:js-translation:dump web/assets --env={{ env }} --merge-domains"
  args:
    chdir: "{{ deploy_helper.new_release_path }}"

- name: Assetic dump
  command: "php bin/console assetic:dump --env={{ env }}"
  args:
    chdir: "{{ deploy_helper.new_release_path }}"

- name: Create eZ legacy symlink directories
  command: "php bin/console ezpublish:legacy:symlink -c --force --env={{ env }}"
  args:
    chdir: "{{ deploy_helper.new_release_path }}"

- name: Create eZ legacy symlink directories web
  command: "php bin/console ezpublish:legacy:assets_install --relative --symlink --force --env={{ env }}"
  args:
    chdir: "{{ deploy_helper.new_release_path }}"

- name: Create Conversa eZ legacy symlink directories
  command: "php bin/console conversa:ezpublish:symlink --force --env={{ env }}"
  args:
    chdir: "{{ deploy_helper.new_release_path }}"

- name: EzPublish generate autoloads
  command: "php bin/php/ezpgenerateautoloads.php"
  args:
    chdir: "{{ deploy_helper.new_release_path }}/ezpublish_legacy"
