# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `ezplatform_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/staging/vault.yml

ezplatform_sites:
  ezplatform.com:
    site_hosts:
      - canonical: staging.ezplatform.com
#        redirects:
#          - otherdomain.com
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo_subtree_path: site
    deploy_keep_releases: 3
    branch: dev
    ssl:
      enabled: false
    cache:
      enabled: false
