---
- import_tasks: database.yml
  tags: ezplatform-setup-database
- import_tasks: self-signed-certificate.yml
  tags: ezplatform-setup-self-signed-certificate
- import_tasks: nginx-client-cert.yml
  tags: ezplatform-setup-nginx-client-cert

- name: Create web root
  file:
    path: "{{ www_root }}"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0755
    state: directory

- name: Create logs folder of sites
  file:
    path: "{{ www_root }}/{{ item.key }}/logs"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0755
    state: directory
  with_dict: "{{ ezplatform_sites }}"

- name: Create EzPlatform php-fpm configuration file
  template:
    src: php-fpm.conf.j2
    dest: /etc/php/7.2/fpm/pool.d/ezplatform.conf
  notify: reload php-fpm

- name: Disable default PHP-FPM pool
  command: mv /etc/php/7.2/fpm/pool.d/www.conf /etc/php/7.2/fpm/pool.d/www.disabled
  args:
    creates: /etc/php/7.2/fpm/pool.d/www.disabled
  when: disable_default_pool | default(true)
  notify: reload php-fpm

- import_tasks: nginx-includes.yml
  tags: [nginx-includes, ezplatform-setup-nginx]

- import_tasks: nginx.yml
  tags: ezplatform-setup-nginx

- name: Install eZ Platform
  command: "php bin/console ezplatform:install clean"
  args:
    chdir: "{{ www_root }}/{{ item.key }}/{{ item.value.current_path | default('current') }}/"
  with_dict: "{{ ezplatform_sites }}"
