site_uses_local_db: "{{ site_env.database_host == 'localhost' }}"
nginx_ezplatform_site_conf: ezplatform-site.conf.j2
nginx_ssl_path: "{{ nginx_path }}/ssl"

ssl_default_site:
  no_default:
    site_hosts:
      - canonical: example.com
    ssl:
      enabled: true
      provider: self-signed
    multisite: {}

nginx_sites_confs:
  - src: no-default.conf.j2
  - src: ssl.no-default.conf.j2
    enabled: "{{ sites_use_ssl }}"

# HSTS defaults
nginx_hsts_max_age: 31536000
nginx_hsts_include_subdomains: true
nginx_hsts_preload: false

# HSTS helpers
hsts_max_age: "{{ item.value.ssl.hsts_max_age | default(nginx_hsts_max_age) }}"
hsts_include_subdomains: "{{ item.value.ssl.hsts_include_subdomains | default(nginx_hsts_include_subdomains) | ternary('includeSubDomains', None) }}"
hsts_preload: "{{ item.value.ssl.hsts_preload | default(nginx_hsts_preload) | ternary('preload', None) }}"

# Fastcgi cache params
nginx_cache_duration: 30s
nginx_skip_cache_uri: /site_admin/|/admin/|/api/|/graphql/|/_wdt/|/ngadminui/|sitemap(_index)?.xml
nginx_skip_cache_cookie: eZSESSID[a-f0-9]+
nginx_cache_background_update: "on"

# Nginx includes
nginx_includes_templates_path: nginx-includes
nginx_includes_deprecated: roles/ezplatform/templates/ez_params.d
nginx_includes_pattern: "^({{ nginx_includes_templates_path | regex_escape }}|{{ nginx_includes_deprecated | regex_escape }})/(.*)\\.j2$"
nginx_includes_d_cleanup: true

# h5bp helpers
not_dev: "{{ env != 'dev' }}"
h5bp: "{{ item.value.h5bp | default({}) }}"
h5bp_cache_file_descriptors_enabled: "{{ h5bp.cache_file_descriptors | default(not_dev) }}"
h5bp_extra_security_enabled: "{{ h5bp.extra_security | default(true) }}"
h5bp_no_transform_enabled: "{{ h5bp.no_transform | default(false) }}"
h5bp_x_ua_compatible_enabled: "{{ h5bp.x_ua_compatible | default(true) }}"
h5bp_cache_busting_enabled: "{{ h5bp.cache_busting | default(false) }}"
h5bp_cross_domain_fonts_enabled: "{{ h5bp.cross_domain_fonts | default(true) }}"
h5bp_expires_enabled: "{{ h5bp.expires | default(false) }}"
h5bp_protect_system_files_enabled: "{{ h5bp.protect_system_files | default(true) }}"

# PHP FPM
#; Choose how the process manager will control the number of child processes.
#; Possible Values:
#  ;   static  - a fixed number (pm.max_children) of child processes;
#  ;   dynamic - the number of child processes are set dynamically based on the
#  ;             following directives. With this process management, there will be
#  ;             always at least 1 children.
#  ;             pm.max_children      - the maximum number of children that can
#  ;                                    be alive at the same time.
#  ;             pm.start_servers     - the number of children created on startup.
#  ;             pm.min_spare_servers - the minimum number of children in 'idle'
#  ;                                    state (waiting to process). If the number
#  ;                                    of 'idle' processes is less than this
#  ;                                    number then some children will be created.
#  ;             pm.max_spare_servers - the maximum number of children in 'idle'
#  ;                                    state (waiting to process). If the number
#  ;                                    of 'idle' processes is greater than this
#  ;                                    number then some children will be killed.
#  ;  ondemand - no children are created at startup. Children will be forked when
#;             new requests will connect. The following parameter are used:
#  ;             pm.max_children           - the maximum number of children that
#  ;                                         can be alive at the same time.
#  ;             pm.process_idle_timeout   - The number of seconds after which
#  ;                                         an idle process will be killed.
#; Note: This value is mandatory.
php_fpm_pm: dynamic
php_fpm_pm_max_children: 15
php_fpm_pm_start_servers: 10
php_fpm_pm_min_spare_servers: 10
php_fpm_pm_max_spare_servers: 15
php_fpm_pm_max_requests: 500

